trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - environments/*
      - azure-pipelines-apply.yml

variables:
  - group: terraform-secrets

stages:
  - stage: Validate
    displayName: Validate
    jobs:
      - job: tf_validate
        pool:
          vmImage: ubuntu-latest
        displayName: tf_validate
        steps:
        - task: TerraformInstaller@1
          displayName: tf_install
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: tf_init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            backendServiceArm: 'Azure-upgraded-SN'
            backendAzureRmResourceGroupName: 'terraform-state-rg'
            backendAzureRmStorageAccountName: 'devtfstate5728'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          displayName: tf_validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
  
  - stage: Dev_Deploy
    displayName: Dev_Deploy
    dependsOn: Validate
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')
    jobs:
      - job: tf_dev_deploy
        displayName: tf_dev_deploy
        steps:
        - task: TerraformInstaller@1
          displayName: tf_install
          inputs:
            terraformVersion: 'latest'
        - script: |
            echo "KEY = $(ssh_public_key)"
          displayName: Debug SSH Key
        - task: TerraformTask@5
          displayName: tf_init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            backendServiceArm: 'Azure-upgraded-SN'
            backendAzureRmResourceGroupName: 'terraform-state-rg'
            backendAzureRmStorageAccountName: 'devtfstate5728'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          displayName: tf_plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            environmentServiceNameAzureRM: 'Azure-upgraded-SN'
          env:
            TF_VAR_ssh_public_key: $(ssh_public_key)
        - task: TerraformTask@5
          displayName: tf_apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            commandOptions: '--auto-approve'
            environmentServiceNameAzureRM: 'Azure-upgraded-SN'
          env:
            TF_VAR_ssh_public_key: $(ssh_public_key)

  - stage: Stage_Deploy
    displayName: Stage_Deploy
    dependsOn: Dev_Deploy
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')
    jobs:
      - job: tf_stage_deploy
        displayName: tf_stage_deploy
        steps:
        - task: TerraformInstaller@1
          displayName: tf_install
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: tf_init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/stage'
            backendServiceArm: 'Azure-upgraded-SN'
            backendAzureRmResourceGroupName: 'terraform-state-rg'
            backendAzureRmStorageAccountName: 'stagetfstate5681'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          displayName: tf_plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/stage'
            environmentServiceNameAzureRM: 'Azure-upgraded-SN'
          env:
            TF_VAR_ssh_public_key: $(ssh_public_key)
        - task: TerraformTask@5
          displayName: tf_apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/stage'
            commandOptions: '--auto-approve'
            environmentServiceNameAzureRM: 'Azure-upgraded-SN'
          env:
            TF_VAR_ssh_public_key: $(ssh_public_key)


